version: '2'
services:
  db:
    image: postgres:12.4-alpine
    container_name: lab7
    hostname: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
#    restart: always